.TH IOLOAD 1 "2007-06-06" "ioload"
.SH NAME
ioload \- generates file I/O load
.SH SYNOPSIS
\fBioload\fP "workfile"
.SH DESCRIPTION
\fIIoload\fP is a small tool that can be used to generate file I/O
load. It opens the specified workfile and will perform read and
write operations to the file for the purpose of generating I/O stress.
.PP
Please note that the tool expects the workfile to already exist (and
have suitable permissions). A quick way to create the workfile is to
use dd (the example creates an one-megabyte workfile):
.PP
.RS
\fBdd if=/dev/zero of=workfile count=1024 bs=1024\fP
.RE
.PP
After starting ioload it will perform I/O operations until
terminated. Status information will be written to stdout periodically
while the tool is running. Please note that the original contents of
the workfile will be destroyed during runtime.
.SH OPTIONS
Currently, the tool does not have actual options. It only expects the
name of the workfile as an argument.
.SH SEE ALSO
.IR cpuload (1),
.IR memload (1)
.SH COPYRIGHT
Copyright (C) 2007 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.