#!/bin/sh

# This file is part of sp-stress
#
# Copyright (C) 2007 Nokia Corporation.
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA

# at least two args, timeout >= 1, command in path?
if [ $# -lt 2 ] || [ $1 -lt 1 ] || [ -z $(which $2) ]; then
  echo "usage: ${0##*/} <timeout> <command> [command args]"

  exit 1
fi
sleep=$1
shift
$* &
pid=$!
sleep $sleep
kill -KILL $pid
